# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(715, 446)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(226, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 220, 51, 21))
        self.label_3.setObjectName("label_3")
        self.txtInformation = QtWidgets.QTextEdit(Form)
        self.txtInformation.setGeometry(QtCore.QRect(110, 90, 241, 101))
        self.txtInformation.setObjectName("txtInformation")
        self.txtSignature = QtWidgets.QTextEdit(Form)
        self.txtSignature.setGeometry(QtCore.QRect(110, 210, 241, 91))
        self.txtSignature.setObjectName("txtSignature")
        self.btnGeneratekeys = QtWidgets.QPushButton(Form)
        self.btnGeneratekeys.setGeometry(QtCore.QRect(330, 40, 91, 21))
        self.btnGeneratekeys.setObjectName("btnGeneratekeys")
        self.btnSign = QtWidgets.QPushButton(Form)
        self.btnSign.setGeometry(QtCore.QRect(90, 360, 75, 23))
        self.btnSign.setObjectName("btnSign")
        self.btnVerify = QtWidgets.QPushButton(Form)
        self.btnVerify.setGeometry(QtCore.QRect(330, 360, 75, 23))
        self.btnVerify.setObjectName("btnVerify")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ECC Cipher"))
        self.label_2.setText(_translate("Form", "Information"))
        self.label_3.setText(_translate("Form", "Signature"))
        self.btnGeneratekeys.setText(_translate("Form", "Generate Keys"))
        self.btnSign.setText(_translate("Form", "Sign"))
        self.btnVerify.setText(_translate("Form", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
