# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(824, 474)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 280, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(410, 130, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(410, 270, 47, 13))
        self.label_5.setObjectName("label_5")
        self.txtplaintext = QtWidgets.QTextBrowser(Form)
        self.txtplaintext.setGeometry(QtCore.QRect(90, 120, 256, 101))
        self.txtplaintext.setReadOnly(False)
        self.txtplaintext.setObjectName("txtplaintext")
        self.txtciphertext = QtWidgets.QTextBrowser(Form)
        self.txtciphertext.setGeometry(QtCore.QRect(90, 250, 256, 101))
        self.txtciphertext.setReadOnly(False)
        self.txtciphertext.setObjectName("txtciphertext")
        self.txtInfomation = QtWidgets.QTextBrowser(Form)
        self.txtInfomation.setGeometry(QtCore.QRect(500, 120, 256, 101))
        self.txtInfomation.setReadOnly(False)
        self.txtInfomation.setObjectName("txtInfomation")
        self.txtsignature = QtWidgets.QTextBrowser(Form)
        self.txtsignature.setGeometry(QtCore.QRect(500, 250, 256, 111))
        self.txtsignature.setReadOnly(False)
        self.txtsignature.setObjectName("txtsignature")
        self.btnGeneratekeys = QtWidgets.QPushButton(Form)
        self.btnGeneratekeys.setGeometry(QtCore.QRect(380, 30, 81, 21))
        self.btnGeneratekeys.setObjectName("btnGeneratekeys")
        self.btnEncrypt = QtWidgets.QPushButton(Form)
        self.btnEncrypt.setGeometry(QtCore.QRect(30, 390, 75, 23))
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnDecrypt = QtWidgets.QPushButton(Form)
        self.btnDecrypt.setGeometry(QtCore.QRect(200, 390, 75, 23))
        self.btnDecrypt.setObjectName("btnDecrypt")
        self.btnSign = QtWidgets.QPushButton(Form)
        self.btnSign.setGeometry(QtCore.QRect(390, 390, 75, 23))
        self.btnSign.setObjectName("btnSign")
        self.btnVerify = QtWidgets.QPushButton(Form)
        self.btnVerify.setGeometry(QtCore.QRect(590, 390, 75, 23))
        self.btnVerify.setObjectName("btnVerify")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "RSA CIPHER"))
        self.label_2.setText(_translate("Form", "Plain Text"))
        self.label_3.setText(_translate("Form", "CipherText:"))
        self.label_4.setText(_translate("Form", "Information:"))
        self.label_5.setText(_translate("Form", "Signature:"))
        self.btnGeneratekeys.setText(_translate("Form", "Generate Keys"))
        self.btnEncrypt.setText(_translate("Form", "Encrypt"))
        self.btnDecrypt.setText(_translate("Form", "Decrypt"))
        self.btnSign.setText(_translate("Form", "Sign"))
        self.btnVerify.setText(_translate("Form", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
